### ISSUE TITLE
Exception raised in delete_file() method when previously no file exists

### ISSUE THREAD

**Issue by snig-b** [un1t/django-cleanup#13]
Full traceback:

    ERROR Unexpected exception while attempting to delete file ''
    Traceback (most recent call last):
      File "/home/ubuntu/.virtualenvs/home/local/lib/python2.7/site-packages/django_cleanup/models.py", line 62, in delete_file
        storage.delete(file_.name)
      File "/home/ubuntu/.virtualenvs/home/local/lib/python2.7/site-    packages/django/core/files/storage.py", line 231, in delete
        assert name, "The name argument is not allowed to be empty."
    AssertionError: The name argument is not allowed to be empty.

If previously a file does not exist in the model instance, and a new one is being uploaded, the old_file gets the value None, and it is sent for deletion without checking whether that file actually exists or not. 

    if old_file != new_file:
            delete_file(old_file)       # in L36 in models.py `

And storage.exists(file_.name) comes out to be true for empty name.

**Comment by snig-b** [comment]
And on S3 the following error is raised:

    ValueError: Empty key names are not allowed
    (16 additional frame(s) were not displayed)
    ...
      File "django/dispatch/dispatcher.py", line 185, in send
        response = receiver(signal=self, sender=sender, **named)
      File "django_cleanup/models.py", line 37, in remove_old_files
        delete_file(old_file)
      File "django_cleanup/models.py", line 49, in delete_file
        if storage and storage.exists(file_.name):
      File "storages/backends/s3boto.py", line 413, in exists
        k = self.bucket.new_key(self._encode_name(name))
      File "boto/s3/bucket
     .py", line 622, in new_key
        raise ValueError('Empty key names are not allowed')

**Comment by un1t** [comment]
Thank you for details. This commit should fix this
https://github.com/un1t/django-cleanup/commit/7973b19d6c96e68bded84ccc1d9166ea12c1d59b
