### ISSUE TITLE
PermissionError: There was an exception deleting the file because it is being used by another process

### ISSUE THREAD

**Issue by ggmblr** [un1t/django-cleanup#84]
Strange kind of bug i came across.

When initiating a model instance, and then opening it in the admin page as if i were to modify it, simpli saving without making any changes prompts me with the following traceback:
```
There was an exception deleting the file `logo/6000_4000.webp` on field `accounts.restaurant.logo`
Traceback (most recent call last):

  File "C:\Users\sherzog\web_app\env\lib\site-packages\django_cleanup\handlers.py", line 96, in run_on_commit
    file_.delete(save=False)

  File "C:\Users\sherzog\web_app\env\lib\site-packages\django\db\models\fields\files.py", line 373, in delete
    super().delete(save)

  File "C:\Users\sherzog\web_app\env\lib\site-packages\django\db\models\fields\files.py", line 105, in delete
    self.storage.delete(self.name)

  File "C:\Users\sherzog\web_app\env\lib\site-packages\django\core\files\storage.py", line 304, in delete
    os.remove(name)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\sherzog\\web_app\\backend\\media\\logo\\6000_4000.webp'
```

It seems it is interpreting this as a replacement of the original logo with the same one, or something like this. Should i be worried about this?

**Comment by vinnyrose** [comment]
What version of django_cleanup are you using?

**Comment by ggmblr** [comment]
I'm using `django-cleanup==5.1.0`

**Comment by vinnyrose** [comment]
Can you provide a minimal sample model and field? Typically this happens when either the settings MEDIA_ROOT or the field upload_to is misconfigured.
